### ISSUE TITLE
Issue 1: Mejorar la interfaz del menú.

### ISSUE THREAD

**Issue by ariequeve** [ariequeve/usal-calculadora-basica#1]
Modificar la interfaz de usuario para que en lugar de ingresar el operador, el usuario ingrese un número entre 1 y 4 donde se especifique la siguiente correspondencia para las operaciones:

Suma (+)
Resta (-)
Multiplicación (*)
División (/)

Por lo tanto el usuario deberá ingresar 2 números y el caracter correspodiente para la operación.

**Comment by ariequeve** [comment]
Para resolver este issue, hacer uso del manejo de ramas (branches). De esta forma, podrás trabajar sobre el código sin alterar la rama principal (main)

git checkout -b feature-mejorar-menu

**Comment by ariequeve** [comment]
@Kiiro121r ¿podrías resolver este issue?

**Comment by theoisrael** [comment]
Si claro, necesitas que el usuario ingrese un numero para seleccionar la operación o el símbolo de esta? ya que en el código esta como para seleccionar un numero.

**Comment by ariequeve** [comment]
Claro, en lugar de que la selección de la operación se realice a través de un número como está ahora, debés realizar los cambios para que la selección de la operación se realice a través del símbolo:

Suma "+"
Resta "-"
Multiplicación "*"
División "/"

**Comment by theoisrael** [comment]
Dale entiendo, cuando lo termino como lo mando?

**Comment by ariequeve** [comment]
Seguí el paso a paso que está en el repo (readme file) el mismo que fuiste leyendo al principio.  Ahí está todo lo que tenés que hacer hasta llegar a "pushear" tu código y generar el "Pull Request"

**Comment by ariequeve** [comment]
@Kiiro121r consulta: ¿tu código con las modificacioneas pudiste probarlas y validar que corre correctamente? gracias

**Comment by theoisrael** [comment]
Si lo probé en visual studio code desde mi computadora y funcionaba correctamente
