### ISSUE TITLE
Issue 8: Agregar operación Comparación

### ISSUE THREAD

**Issue by ariequeve** [ariequeve/usal-calculadora-basica#10]
Agregar una operación a la calculadora que permita al usuario seleccionar la mediante el caracter "C" la comparacíon de dós números indicando:
- Si Num1 es Mayor a Num2
- Si Num1 es Menor a Num2
- Si Num1 es Igual a Num2

**Comment by ariequeve** [comment]
@moranmateo ¿podrías trabajar en este issue? Gracias
Quedo a disposición ante cualquier duda.  Abrazo

**Comment by moranmateo** [comment]
Buenas tardes Ariel, quería avisarle que no me aparece el issue número 10.
Lo siento por tardar en responder.

**Comment by ariequeve** [comment]
Hola @moranmateo, este es el issue #8 al que estás asignado.  Tratá de revisar todo en la plataforma de Github así te vas familiarizando con la interfaz de usuario
Abrazo.

**Comment by moranmateo** [comment]
Ahi pude terminar de agregar la funcion de comparacion en el programa, lo unico que no entiendo es como lo podria subir para que se vean los cambios, segui un tutorial de youtube el cual instale github desktop.

**Comment by ariequeve** [comment]
@moranmateo fijate que en el archivo README del repo tenés todas las indicaciones.  Si seguís la receta deberías poder completar el pull request (que es la instancia donde tenés listo tu código para subirlo)
